services:
  chatbot:
    build: .
    ports:
      - "8501:8501"
    environment:
      MODEL_ID: "hosted_vllm/Qwen/Qwen3-0.6B"
      BASE_URL: "http://vllm:8000/v1"

  vllm:
    image: docker.io/vllm/vllm-openai:latest
    container_name: vllm-server
    ports:
      - "8000:8000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: 
      - "--model"
      - "Qwen/Qwen3-0.6B"
      - "--reasoning-parser"
      - "qwen3"
