events {
    worker_connections 1024;
}

http {
    upstream mlflow {
        server mlflow:5000;
    }
    upstream chatbot {
        server chatbot:8501;
    }

    server {
        listen 80;
    
        location / {
            proxy_pass http://chatbot;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    
        location /mlflow/ {
            proxy_pass http://mlflow;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
